### ISSUE TITLE
Don't use shallow copies for pointers

### ISSUE THREAD

**Issue by vvtrunov** [Mikhail038/MY_Hash_tables#1]
I was inspecting ur perfect code and found an error. 
HASH_F/hash.h::94::insert_tail: U're making rvalue object with using {} (initial returning value of ctor), that containing pointer (char *data). That is immediately destructing on the next line (read smth about xvalue or ask me), in destructor that object frees char * pointer.
U can solve it in many ways, as I see, mb u're gonna make deep copy in EXTRA/LIST/simpleList.h::59, if u do that, then u can free ur pointer in destructor of expired rvalue.

**Comment by Mikhail038** [comment]
I've played with copy-constructors and so, and problem seem to be solved.
